steps:
- id: 'pull-latest'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - 'docker pull gcr.io/$PROJECT_ID/apps/aws-encryption-provider:latest || true'

- id: 'build-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--cache-from=gcr.io/$PROJECT_ID/apps/aws-encryption:latest'
  - '--tag=gcr.io/$PROJECT_ID/apps/aws-encryption-provider:$SHORT_SHA'
  - '.'

- id: 'tag-image'
  name: 'gcr.io/$PROJECT_ID/cloud-builders/tagger'
  env:
  - SOURCE_IMAGE=gcr.io/$PROJECT_ID/apps/aws-encryption-provider:$SHORT_SHA
  - IMAGE_NAME=gcr.io/$PROJECT_ID/apps/aws-encryption-provider
  - BRANCH_NAME=$BRANCH_NAME

images: ['gcr.io/$PROJECT_ID/apps/aws-encryption-provider']
